Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
1c1
< bash: line 1: kaas: command not found
---
> minishell: kaas: command not found
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
1c1
< bash: line 1: kaas: command not found
---
> minishell: kaas: command not found
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
1c1
< bash: line 1: kaas: command not found
---
> minishell: kaas: command not found
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
1c1
< bash: line 1: kaas: command not found
---
> minishell: kaas: command not found
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
1c1
< bash: line 1: kaas: command not found
---
> minishell: kaas: command not found
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
Executing: kaas
[ [91m FAIL [0m ]: kaas: output differs
